/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.tutorial;

public class App {
  public static void main(String[] args) {
    Conditionals conditionalsVariable = new Conditionals();
  }
}
